# Generated by Django 6.0.3 on 2026-04-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
