# Generated by Django 6.0.3 on 2026-04-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorbooking_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='appointment_duration',
            field=models.IntegerField(default=30, help_text='Длительность приёма в минутах'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='end_time',
            field=models.TimeField(default='18:00', help_text='Время окончания приёма'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_time',
            field=models.TimeField(default='09:00', help_text='Время начала приёма'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorbooking',
            unique_together={('doctor', 'appointment_date', 'status')},
        ),
    ]
